version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: unless-stopped
    expose:
      - "80"   # expose to other containers

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: unless-stopped
    expose:
      - "8080" # expose to other containers

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS (optional if SSL is configured)
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
