version: "3.8"

services:
  backend:
    build: ./backend
    expose:
      - "8080"   # Map container's 8080 to host's 80 for Cloudflare
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html      # frontend build
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend