version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env


  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=production
