version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "80:8080"   # Map container's 8080 to host's 80 for Cloudflare
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "https://api.latexwriter.com"  # Backend subdomain
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
