version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "https://3.110.212.91:8080"
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production