version: "3.8"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: "https://api.latexwriter.com"
    container_name: frontend
    restart: unless-stopped

  nginx-frontend:
    build: ./nginx-frontend
    container_name: nginx-frontend
    ports:
      - "3000:80"  # Internal port, Cloudflare will handle HTTPS
    depends_on:
      - frontend
    restart: unless-stopped

  nginx-backend:
    build: ./nginx-backend
    container_name: nginx-backend
    ports:
      - "80:80"  # Cloudflare proxies HTTPS here
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    driver: bridge
